### ISSUE TITLE
Translate

### ISSUE THREAD

**Issue by printf-ana** [muchirijane/learning-code-through-github-repos#13]
Hey, i'd like to contributing translating for portuguese. Can i?

**Comment by muchirijane** [comment]
Sure. Let me assign it to you.

**Comment by leaggg** [comment]
Hi, what files would you like to have translated? I could help you with French :)

**Comment by muchirijane** [comment]
Hey @leaggg. 
The most important file is the readme file, you can translate that. 
Here is an example from @printf-ana https://github.com/printf-ana/learning-code-through-github-repos/tree/translation-portuguese

**Comment by leaggg** [comment]
Awesome, I am on it then!

**Comment by muchirijane** [comment]
Cool 👍🏽

**Comment by MicheleMarschner** [comment]
Hi @leaggg, I can do the translation to German.

**Comment by muchirijane** [comment]
@MicheleMarschner, sure. 
Go through the contribution.md file and create a PR. 👍🏽

**Comment by broidea** [comment]
Hey
Would you like a Russian translation?

**Comment by muchirijane** [comment]
Yes. 👍🏽

**Comment by MigueMartelo** [comment]
Hi, I would like to translate to spanish, how I can make it?

**Comment by muchirijane** [comment]
Yeah sure. Click the contribution.md file and see how to make a successful PR. 👍🏽
