### ISSUE TITLE
Translation of the readme file

### ISSUE THREAD

**Issue by muchirijane** [muchirijane/learning-code-through-github-repos#23]
**Is your feature request related to a problem? Please describe.**
The readme file is only in English. If you can translate it to your language it may help others within your community as they learn. 👩‍💻

**Describe the solution you'd like**
Create a folder eg Translation to Chinese. Inside that folder, it will contain the translated readme file. ✨
Please read the contribution.md file before making the PR. ⛔

**Describe alternatives you've considered**
No other alternative. 

**Additional context**
N/A

**Comment by Hackerbone** [comment]
I would Like to take this issue. I would like to translate readme in Hindi..
If you could assign me this then that would be great

**Comment by muchirijane** [comment]
Hey, go ahead. Let me assign it. 
Remember to go through the contribution.md file. 👍🏽

**Comment by Hackerbone** [comment]
Yup sure thanks!

**Comment by Hackerbone** [comment]
@muchirijane can you add the hacktoberfest-accepted label on my PR?
https://github.com/muchirijane/learning-code-through-github-repos/pull/32

**Comment by muchirijane** [comment]
Hey, just added it. 👍🏽

**Comment by Hackerbone** [comment]
Thanks!

**Comment by GriffinMLN** [comment]
@muchirijane hey! Is it okay if I add a Bulgarian translation?

**Comment by muchirijane** [comment]
Hey @GriffinMLN, It's cool. You can 👍🏽

**Comment by onyet** [comment]
Hi. i just add PR for Language Bahasa Indonesia. I hope you like it. 😉

**Comment by muchirijane** [comment]
@onyet Awesome let me merge it. 👍🏽

**Comment by Axel546** [comment]
@muchirijane hey! Is it ok if I add a Romanian Translation?

**Comment by muchirijane** [comment]
@Axel546, yes go ahead. 👍🏽

**Comment by Axel546** [comment]
@muchirijane Done! I added Romanian translation! Hope it is fine! :)

**Comment by muchirijane** [comment]
@Axel546 I have commented on the PR the few things you should change. 💯

**Comment by Axel546** [comment]
Done again! I made a PR in developer branch. Hope it is fine!

**Comment by fcpimenta** [comment]
Hi @muchirijane , I would like to take this issue. I would like to translate readme in Brazilian Portuguese.
Could you assign me this, please?

**Comment by muchirijane** [comment]
Hey @fcpimenta, go ahead. Looking forward to seeing your contribution. 💯

**Comment by fcpimenta** [comment]
Hi, @muchirijane, thanks for the return. But, I noted that the repo already have a Portuguese folder (18 days ago).

**Comment by muchirijane** [comment]
@fcpimenta Hey, you can add a resource to the repo. There a lot of categories I have added, plus you can add another that's not there like Docker resources, etc.
